version: '3'

services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hexfinder-api
    ports:
      - 8080:3000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
